os: osx
language: cpp
addons:
  homebrew:
    packages:
    - scons
    - yaml-cpp
git:
  submodules: false
script: 
  - git submodule update --init --recursive godot-cpp
  - cd godot-cpp
  - scons platform=osx headers=godot_headers generate_bindings=yes target=release
  - cd ..
  - scons platform=osx target=release 